### ISSUE TITLE
Unhandled exception: Unauthorized Access

### ISSUE THREAD

**Issue by tozuf0x** [tremwil/SteamP2PInfo#24]
So I've installed this app and selected a path to steam logs (changed it because I have installed steam elsewhere), however it is giving me access denied exception as I input command into console. I run it as admin and turned windows defender off to no avail. How do I grant access to that folder?

**Comment by tozuf0x** [comment]
Full error message app gives me is
 UnauthorizedAccessException: Access to the path "G:\SteamGames\logs" is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream.ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at SteamP2PInfo.SteamPeerManager.<UpdatePeerList>d__8.MoveNext()
--- end of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   `at` System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by tozuf0x** [comment]
and ipc_SteamClient.log is empty

**Comment by cridus** [comment]
So, did you try manually changing the permissions as I said?

**Comment by tozuf0x** [comment]
Looks like both steamp2p and logs folder are in full access

**Comment by tozuf0x** [comment]
Changing app location to the same drive as steam seemed to solve the issue

**Comment by cridus** [comment]
Then I guess we should check why it uses the wrong drive when the path explicitly defines the correct one.
