### ISSUE TITLE
Crashing on focusing back to the game

### ISSUE THREAD

**Issue by hazylua** [tremwil/SteamP2PInfo#26]
After attaching the game and focusing back to Elden Ring, the application crashes with the following log:
Win32Exception: Invalid window handle
   at MS.Win32.UnsafeNativeMethods.GetMessageW(MSG& msg, HandleRef hWnd, Int32 uMsgFilterMin, Int32 uMsgFilterMax)
   at System.Windows.Threading.Dispatcher.GetMessage(MSG& msg, IntPtr hwnd, Int32 minMessage, Int32 maxMessage)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at SteamP2PInfo.App.Main()
Seems a bit random too, a couple days ago the program was working fine and then it started crashing all of a sudden.

**Comment by tremwil** [comment]
Hi, could you please provide the following information?

- Windows version
- Elden Ring screen mode (windowed, borderless, or fullscreen?)
- contents of the SteamP2PInfo configuration file for Elden ring (should be called `eldenring.json` in the `config` folder next to the executable)
- While you said the program was working fine "a couple days ago", currently, does this bug occur consistently when focus returns to the Elden Ring window, or is this something that happens at random, say for example 1/2 or 1/3 of the time?
- If you are able to consistently reproduce it, what method are you using the select the Elden Ring window (clicking with the mouse, alt+tab, etc.)? Does changing this affect the outcome?

**Comment by hazylua** [comment]
- Window 10 Education Version 10.0.19044 Build 19044
- Elden Ring is running in **borderless windowed** mode
- My eldenring.json: `{
  "process_name": "eldenring",
  "steam_appid": 1245620,
  "set_played_with": true,
  "open_profile_in_overlay": true,
  "log_activity": false,
  "hotkeys_enabled": true,
  "play_sound_on_new_session": false,
  "overlay": {
    "enabled": true,
    "show_steam_id": false,
    "show_connection_quality": true,
    "hotkey": 0,
    "banner_format": "[{time:HH:mm:ss}] SteamP2PInfo - by tremwil",
    "font": "Segoe UI, 20.25pt",
    "x_offset": 0.025,
    "y_offset": 0.025,
    "anchor": 0,
    "text_color": "#FFFFFFFF",
    "stroke_color": "#FF000000",
    "stroke_width": 2.0,
    "ping_colors": [
      {
        "threshold": 0.0,
        "color": "#FF00BFFF"
      },
      {
        "threshold": 50.0,
        "color": "#FF7CFC00"
      },
      {
        "threshold": 100.0,
        "color": "#FFFFFF00"
      },
      {
        "threshold": 200.0,
        "color": "#FFCD5C5C"
      }
    ]
  }
}`
- I was a little mistaken when describing the problem. It occurs every time but it does not only happen when focusing to the game window after being attached, it occurs whenever I click on any other window/anywhere that is not the application window (for example, tabbing out to Firefox or simply clicking somewhere outside the program window)
- As a I said previously, it happens when tabbing out, selecting another window on the taskbar, clicking outside etc. Simply unfocusing the application seems to cause it to crash.

**Comment by tremwil** [comment]
Thanks! Sadly, I wasn't able to recreate the issue with this exact Windows version and settings, but I'll still look into it.
